---
- name: Configure Automation Controller inventory and sources
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    controller_organization: Default
    controller_project: Azure Ansible Inventory Hierarchy
    controller_project_scm_url: "https://github.com/jritter/azure-ansible-inventory-hierarchy.git"
    controller_project_scm_branch: main
    controller_inventory: Azure Lab
    # verbosity: 0 = Warning, 1 = Info, 2 = Debug
    controller_inventory_source_verbosity: 2
    # The playbook assumes that this credential exists and holds the relevant information to access your Azure resources.
    azure_rm_credential: Azure


  tasks:
    - name: Create the project
      ansible.controller.project:
        name: "{{ controller_project }}"
        organization: "{{ controller_organization }}"
        scm_type: git
        scm_url: "{{ controller_project_scm_url }}"
        scm_branch: "{{ controller_project_scm_branch }}"
        scm_credential: "{{ controller_scm_credential | default(omit) }}"
        scm_clean: true
        scm_update_on_launch: true
        state: present

    # ######################################################################
    # All in one inventory containing 3 inventory sources:
    # - Azure RM Configuration file from Git
    # - Group Hierarchy from Git
    # - Combined inventory that includes both the above
    - name: Create the inventory
      ansible.controller.inventory:
        name: "{{ controller_inventory }}"
        organization: "{{ controller_organization }}"
        state: present

    # This inventory source points to the azure inventory plugin configuration.
    # When syncing this inventory source, it will assign group membership based on Azure tags,
    # which don't reflect a hierarchy.
    - name: Create inventory source from azure_rm.yml
      ansible.controller.inventory_source:
        name: "{{ controller_inventory }} - Azure RM"
        inventory: "{{ controller_inventory }}"
        source: scm
        source_project: "{{ controller_project }}"
        source_path: inventory/azure_rm.yml
        credential: "{{ azure_rm_credential }}"
        overwrite: true
        update_on_launch: true
        verbosity: "{{ controller_inventory_source_verbosity }}"
        state: present

    # This inventory source points to a file within the git repository.
    # It only contains the group hierarchy definition.
    - name: Create inventory source from group_hierarchy.yml
      ansible.controller.inventory_source:
        name: "{{ controller_inventory }} - Group Hierarchy"
        inventory: "{{ controller_inventory }}"
        source: scm
        source_project: "{{ controller_project }}"
        source_path: inventory/group_hierarchy.yml
        overwrite: true
        update_on_launch: true
        verbosity: "{{ controller_inventory_source_verbosity }}"
        state: present


    # This inventory source points to the inventory directory.
    # With that configuration, the inventory sync takes all files in the inventory
    # directory into account, and combines them into a single inventory.
    # For example, This allows you to define the group hierarchy in a file,
    # while the group memberships are defined based on Azure Tags.
    - name: Create inventory source from inventory/ directory
      ansible.controller.inventory_source:
        name: "{{ controller_inventory }} - Combined"
        inventory: "{{ controller_inventory }}"
        source: scm
        source_project: "{{ controller_project }}"
        source_path: inventory/
        credential: "{{ azure_rm_credential }}"
        overwrite: true
        update_on_launch: true
        verbosity: "{{ controller_inventory_source_verbosity }}"
        state: present

    # ######################################################################
    # Inventory per source
    # - Group Hierarchy from Git
    # - Azure RM

    # Group Hierarchy inventory from Git
    - name: Create the Group Hierarchy inventory
      ansible.controller.inventory:
        name: "{{ controller_inventory }} - Group Hierarchy Only"
        organization: "{{ controller_organization }}"
        state: present

    - name: Create inventory source for Group Hierarchy Only
      ansible.controller.inventory_source:
        name: "{{ controller_inventory }} - Group Hierarchy Only - Source"
        inventory: "{{ controller_inventory }} - Group Hierarchy Only"
        source: scm
        source_project: "{{ controller_project }}"
        source_path: inventory/group_hierarchy.yml
        overwrite: true
        update_on_launch: true
        verbosity: "{{ controller_inventory_source_verbosity }}"
        state: present


    # Azure RM inventory from Azure RM Inventory source type
    - name: Create the Azure RM inventory
      ansible.controller.inventory:
        name: "{{ controller_inventory }} - Azure RM Only"
        organization: "{{ controller_organization }}"
        state: present

    - name: Create inventory source for Azure RM Only
      ansible.controller.inventory_source:
        name: "{{ controller_inventory }} - Azure RM Only - Source"
        inventory: "{{ controller_inventory }} - Azure RM Only"
        source: azure_rm # This is different from the example above, we are not pointing to the azure_rm.yml file
        credential: "{{ azure_rm_credential }}"
        overwrite: true
        update_on_launch: true
        verbosity: "{{ controller_inventory_source_verbosity }}"
        state: present
        source_vars: # The plugin can be parametrized here, no need for a file in Git
          plain_host_names: true
          leading_separator: false
          keyed_groups:
            - key: tags['ansible_group']

    # The constructed inventory merges both the Azure RM inventory and the Group Hierarchy in a consistent way.
    # The Job templates are pointing to the constructed inventory, not the individual inventories.
    # Documentation:
    # https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/constructed_inventory.html
    # Blog Post:
    # https://www.redhat.com/en/blog/how-to-use-the-new-constructed-inventory-feature-in-aap-2.4
    #
    - name: Create the Combined Constructed inventory
      ansible.controller.inventory:
        name: "{{ controller_inventory }} - Constructed"
        organization: "{{ controller_organization }}"
        kind: constructed
        input_inventories:
          - "{{ controller_inventory }} - Group Hierarchy Only"
          - "{{ controller_inventory }} - Azure RM Only"
        state: present

    - name: Configure the Constructed inventory source
      ansible.controller.inventory_source:
        name: "Auto-created source for: {{ controller_inventory }} - Constructed"
        inventory: "{{ controller_inventory }} - Constructed"
        overwrite: true
        update_on_launch: true
        verbosity: "{{ controller_inventory_source_verbosity }}"
        source_vars:
          plugin: constructed
        state: present
